apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viewer-binding-robin
subjects:
- kind: User
  name: robin # Replace with the actual username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: viewer-all
  apiGroup: rbac.authorization.k8s.io