apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-large-1
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: csi.hetzner.cloud
    volumeHandle: "102294559" #volume id
    fsType: ext4