apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jan.matter@dataplumbers.ch
    privateKeySecretRef:
      name: letsencrypt-test
    solvers:
    - http01:
        ingress:
          class: nginx